//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Laborers.Behaviors.Buildings
{
		public struct BuildingData
		{
				public byte[,,] data;
				public int Width {
						get;
						set;
				}
		
				public int Height {
						get;
						set;
				}
		}
		public class BuildingRowData : List<byte>
		{
		}
}

